### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by Hongbo-Miao** [Cherry/network-error-logging#19]
It would be great to have TypeScript support : )

**Comment by Cherry** [comment]
Thanks for the suggestion @Hongbo-Miao! I don't personally use TypeScript so won't be adding this myself any time soon unfortunately, but would encourage a PR if you wish to add this functionality.

**Comment by aaronleopold** [comment]
Hey there, I can look into Typescript support if you would like (I use it more and more lately)!

**Comment by Cherry** [comment]
Please do! I don't know if @Hongbo-Miao has any input or insight into what they're looking for here with the TS support. TS isn't my forte, so I'll be leaning heavily on what you all think is the best way to approach this.

**Comment by Hongbo-Miao** [comment]
No, I don't. Go ahead @aaronleopold !
BTW, I am surprised not a lot of people not aware of this package.

**Comment by aaronleopold** [comment]
I *believe* I'm almost done! Just a quick clarification on some of the fields for the options object.

Am I correct in that the only required field is max_age? All the others are not mandatory?

**Comment by Cherry** [comment]
`max_age` is the only technically required field, yes. The others are optional under different circumstances.

**Comment by Cherry** [comment]
Closed in #29, thanks @aaronleopold. Let me know if there's anything else you'd like to see @Hongbo-Miao!

**Comment by Hongbo-Miao** [comment]
Just tried version

```
"network-error-logging": "git://github.com/Cherry/network-error-logging#aeabd5e1efc2dcf2a0e001c31d842ec165a163d6",
```

it looks good. Thanks @aaronleopold !

@Cherry I think you can bump the package.json version : )

**Comment by Cherry** [comment]
Thanks for testing @Hongbo-Miao! I'll draft a new version soon.

**Comment by Cherry** [comment]
1.2.1 has now been released which includes these changes. Thanks again @aaronleopold for the contribution, and @Hongbo-Miao for the suggestion and further testing!
